package realtime

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/redis/go-redis/v9"
)

// PutOAuthState stores a short-lived, opaque OAuth transaction. OAuth state is
// coordination data rather than durable product data, so Redis is its source
// of truth. The key is generated by the caller and may never be overwritten.
func (b *RedisBus) PutOAuthState(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	if key == "" || len(value) == 0 || ttl <= 0 {
		return fmt.Errorf("invalid OAuth state")
	}
	created, err := b.client.SetNX(ctx, key, value, ttl).Result()
	if err != nil {
		return err
	}
	if !created {
		return fmt.Errorf("OAuth state collision")
	}
	return nil
}

// ConsumeOAuthState atomically reads and deletes a transaction. This makes
// authorization codes single-use even when callbacks reach different nodes.
func (b *RedisBus) ConsumeOAuthState(ctx context.Context, key string) ([]byte, bool, error) {
	value, err := b.client.GetDel(ctx, key).Bytes()
	if errors.Is(err, redis.Nil) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	return value, true, nil
}

func spotifyUserEpochKey(userID string) string {
	return "oauth:spotify:user_epoch:" + userID
}

// GetUserOAuthEpoch returns the current epoch counter for a user's Spotify connection.
func (b *RedisBus) GetUserOAuthEpoch(ctx context.Context, userID string) (int64, error) {
	val, err := b.client.Get(ctx, spotifyUserEpochKey(userID)).Int64()
	if errors.Is(err, redis.Nil) {
		return 0, nil
	}
	return val, err
}

// BumpUserOAuthEpoch atomically increments the epoch counter for a user's Spotify connection,
// invalidating any pending OAuth callbacks that were initiated before the bump.
func (b *RedisBus) BumpUserOAuthEpoch(ctx context.Context, userID string) (int64, error) {
	return b.client.Incr(ctx, spotifyUserEpochKey(userID)).Result()
}
